sudo: false

# Only run travis on the master branch (and PRs), not all branches
branches:
  only:
    - master

language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

git:
  depth: 5

install:
  - travis_retry npm install

script:
  - npm run eslint
  - npm run test
